### ISSUE TITLE
Can not reproduce the results

### ISSUE THREAD

**Issue by AlirezaSalehy** [FuNz-0/PromptAD#15]
Hi, thanks for your research effort! 

Actually, there is no way i can reproduce the results by really far margin. Can you please put the selected hyperparameters that are used for reporting results? 

Thanks 
Regards.

**Comment by FuNz-0** [comment]
Which results are not reproduced by your? Please provide your hyper-parameters and corresponding results.



***@***.***
 
From: Alireza Salehy
Date: 2024-08-09 12:58
To: FuNz-0/PromptAD
CC: Subscribed
Subject: [FuNz-0/PromptAD] Can not reproduce the results (Issue #15)
Hi, thanks for your research effort!
Actually, there is no way i can reproduce the results by really far margin. Can you please put the selected hyperparameters that are used for reporting results?
Thanks
Regards.

**Comment by AlirezaSalehy** [comment]
I have only tried the code for classification, yet. The hyperparameters are mostly the default ones but the `n_ctx_ab` was defaulted to `100` which caused exception during execution. After inspecting the papers provided information, I set it to `1`. 

I also tried for `1` `epoch` but because i couldn't yield the results, I tested with `10` `epochs` but that didn't work as well. 

![image](https://github.com/user-attachments/assets/dab4214d-50cf-4fe7-836e-4d05f6d89402)

**Comment by chuliyou** [comment]
> Which results are not reproduced by your? Please provide your hyper-parameters and corresponding results. ***@***.*** From: Alireza Salehy Date: 2024-08-09 12:58 To: FuNz-0/PromptAD CC: Subscribed Subject: [FuNz-0/PromptAD] Can not reproduce the results (Issue #15) Hi, thanks for your research effort! Actually, there is no way i can reproduce the results by really far margin. Can you please put the selected hyperparameters that are used for reporting results? Thanks Regards. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hello, you don't seem to have mentioned the number of training epochs in your article. May I ask what your epoch setting was during the experiment? Was it the default value of 1 from the source code?

**Comment by AlirezaSalehy** [comment]
Yes I tried for epoch value of 1 and also 10 as well. But I couldn't reproduce the result unfortunately. Thanks for instant reply.

**Comment by FuNz-0** [comment]
set epoch as 100



***@***.***
 
From: Alireza Salehy
Date: 2024-08-09 20:58
To: FuNz-0/PromptAD
CC: FuNz; Comment
Subject: Re: [FuNz-0/PromptAD] Can not reproduce the results (Issue #15)
Yes I tried for epoch value of 1 and also 10 as well. But I couldn't reproduce the result unfortunately. Thanks for instant reply.

**Comment by AlirezaSalehy** [comment]
Yes, now I can reproduce the results executing the train_cls.py. Thank a lot!

In the train_cls.py the default value for n_ctx_ab argument is 100 and for epoch is 1. That made lots of confusion for me.
