### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by liumufenghua** [FuNz-0/PromptAD#26]
测试了full-shot，发现了几个问题，想请教一下。首先是在一些类中full-shot的指标表现还不如few-shot，这有原因吗？promptad在不同类的表现差异较大，导致其跟patchcore的平均指标相差不大，需要调参吗？

**Comment by FuNz-0** [comment]
我们没有做过fullshot 的相关实验，可能一些技术细节需要改一改，还有可能prompt learning 不适用于full shot&nbsp;





------------------ 原始邮件 ------------------
发件人: liumufenghua ***@***.***&gt;
发送时间: 2024年12月27日 09:27
收件人: FuNz-0/PromptAD ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [FuNz-0/PromptAD] 性能问题 (Issue #26)





 
测试了full-shot，发现了几个问题，想请教一下。首先是在一些类中full-shot的指标表现还不如few-shot，这有原因吗？promptad在不同类的表现差异较大，导致其跟patchcore的平均指标相差不大，需要调参吗？

**Comment by liumufenghua** [comment]
非常感谢！
