### ISSUE TITLE
run_seg.py shots有什么含义？

### ISSUE THREAD

**Issue by Drm-hello** [FuNz-0/PromptAD#8]
从代码看就是单纯的控制循环次数，每个类别在不同的循环里跑出来的结果都是一样的，所以设计成[1,2,4]有什么特殊含义吗？它并没有按照论文所说的那样起作用
1-shot
Object:carpet =========================== Pixel-AUROC:99.53
Object:grid =========================== Pixel-AUROC:98.14
Object:leather =========================== Pixel-AUROC:99.39
Object:tile =========================== Pixel-AUROC:96.05
Object:wood =========================== Pixel-AUROC:95.82
Object:bottle =========================== Pixel-AUROC:97.31
Object:cable =========================== Pixel-AUROC:94.3
Object:capsule =========================== Pixel-AUROC:95.35
Object:hazelnut =========================== Pixel-AUROC:98.28
Object:metal_nut =========================== Pixel-AUROC:91.6
Object:pill =========================== Pixel-AUROC:93.61
Object:screw =========================== Pixel-AUROC:93.63
Object:toothbrush =========================== Pixel-AUROC:98.71
Object:transistor =========================== Pixel-AUROC:85.68
Object:zipper =========================== Pixel-AUROC:94.05

2-shot
Object:carpet =========================== Pixel-AUROC:99.53
Object:grid =========================== Pixel-AUROC:98.14
Object:leather =========================== Pixel-AUROC:99.39
Object:tile =========================== Pixel-AUROC:96.05
Object:wood =========================== Pixel-AUROC:95.82
Object:bottle =========================== Pixel-AUROC:97.31
Object:cable =========================== Pixel-AUROC:94.3
Object:capsule =========================== Pixel-AUROC:95.35
Object:hazelnut =========================== Pixel-AUROC:98.28
Object:metal_nut =========================== Pixel-AUROC:91.6
Object:pill =========================== Pixel-AUROC:93.61
Object:screw =========================== Pixel-AUROC:93.63
Object:toothbrush =========================== Pixel-AUROC:98.71
Object:transistor =========================== Pixel-AUROC:85.68
Object:zipper =========================== Pixel-AUROC:94.05

4-shot
Object:carpet =========================== Pixel-AUROC:99.53
Object:grid =========================== Pixel-AUROC:98.14
Object:leather =========================== Pixel-AUROC:99.39
Object:tile =========================== Pixel-AUROC:96.05
Object:wood =========================== Pixel-AUROC:95.82
Object:bottle =========================== Pixel-AUROC:97.31
Object:cable =========================== Pixel-AUROC:94.3
Object:capsule =========================== Pixel-AUROC:95.35
Object:hazelnut =========================== Pixel-AUROC:98.28
Object:metal_nut =========================== Pixel-AUROC:91.6
Object:pill =========================== Pixel-AUROC:93.61
Object:screw =========================== Pixel-AUROC:93.63
Object:toothbrush =========================== Pixel-AUROC:98.71
Object:transistor =========================== Pixel-AUROC:85.68
Object:zipper =========================== Pixel-AUROC:94.05

另外，以默认参数运行run_seg.py，得到的pixel-level的AUROC达不到论文精度，相差较远，是否有什么特别的设定需要更改

**Comment by FuNz-0** [comment]
你好：
    应该是还有一个k-shot的超参数，我们整理代码的时候遗漏掉了，多谢提醒，已修改。



***@***.***
 
发件人： Drm-hello
发送时间： 2024-06-04 10:29
收件人： FuNz-0/PromptAD
抄送： Subscribed
主题： [FuNz-0/PromptAD] run_seg.py shots有什么含义？ (Issue #8)
从代码看就是单纯的控制循环次数，不同类别跑出来的结果也都是一样，所以设计成[1,2,4]有什么特殊含义吗？
―
